baseURL = 'https://koromaki88-blog.pages.dev/'
languageCode = 'en-us'
title = "koromaki88"
theme = 'PaperMod'

[params]
env = 'production'
defaultTheme = 'dark'
disableThemeToggle = true
ShowReadingTime = true
ShowToc = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true
subtitle = "IT/SE student - Technology enthusiast"
imageUrl = "https://avatars.githubusercontent.com/u/86962625"
imageWidth = 250
imageHeight = 250

[[params.profileMode.buttons]]
name = "Posts"
url = "/posts"
[[params.profileMode.buttons]]
name = "CTF Writeups"
url = "/categories/ctf-writeups/"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/koromaki88"
[[params.socialIcons]]
name = "YouTube"
url = "https://www.youtube.com/@koromaki88"
[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/realkoromaki88"
[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/nhiennguyen88/"
[[params.socialIcons]]
name = "Facebook"
url = "https://www.facebook.com/koromaki88/"

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  # limit = 100
  keys = ["title"]

[params.editPost]
  URL = "https://github.com/koromaki88/koromaki88-pages/blob/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

[outputs]
home = ['HTML', 'RSS', 'JSON']

[menu]
[[menu.main]]
identifier = 'search'
name = 'Search'
url = '/search/'
weight = 10
[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'
weight = 20
[[menu.main]]
identifier = 'categories'
name = 'Categories'
url = '/categories/'
weight = 30
[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
weight = 40
[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 50
