baseURL = 'https://koromaki88.pages.dev/'
languageCode = 'en-us'
title = "koromaki88"
theme = 'PaperMod'
customCSS = ['/justify.css', '/gruvbox.css']

[params]
env = 'production'
defaultTheme = 'auto'
ShowReadingTime = true
[params.profileMode]
enabled = true
subtitle = "IT/SE student - Technology enthusiast"
imageUrl = "https://avatars.githubusercontent.com/u/86962625"
imageWidth = 250
imageHeight = 250
[[params.profileMode.buttons]]
name = "Posts"
url = "/posts"
[[params.profileMode.buttons]]
name = "CTF Writeups"
url = "/tags/ctf/"
[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/koromaki88"
[[params.socialIcons]]
name = "YouTube"
url = "https://www.youtube.com/@koromaki88"
[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/realkoromaki88"
[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/nhiennguyen88/"
[[params.socialIcons]]
name = "Facebook"
url = "https://www.facebook.com/koromaki88/"

[menu]
[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'
weight = 10
[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 20
